
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Linux -  - x86_64
      The host system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang.exe 
      Build flags: 
      Id flags: -c;--target=x86_64-linux-gnu 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/3.30.5/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags: -c;--target=x86_64-linux-gnu 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/CMakeScratch/TryCompile-k66523"
      binary: "C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/CMakeScratch/TryCompile-k66523"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_CXX_COMPILER_TARGET: "x86_64-linux-gnu"
      CMAKE_C_COMPILER_TARGET: "x86_64-linux-gnu"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/CMakeScratch/TryCompile-k66523'
        
        Run Build Command(s): C:/ProgramData/chocolatey/bin/ninja.exe -v cmTC_40780
        [1/2] C:\\PROGRA~1\\LLVM\\bin\\clang.exe --target=x86_64-linux-gnu   -v -MD -MT CMakeFiles/cmTC_40780.dir/CMakeCCompilerABI.c.o -MF CMakeFiles\\cmTC_40780.dir\\CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_40780.dir/CMakeCCompilerABI.c.o -c "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeCCompilerABI.c"
        clang version 19.1.0
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: C:\\Program Files\\LLVM\\bin
         (in-process)
         "C:\\\\Program Files\\\\LLVM\\\\bin\\\\clang.exe" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb "-fdebug-compilation-dir=C:\\\\Users\\\\sylva\\\\projekt\\\\sudokill\\\\build-linux\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-k66523" -v "-fcoverage-compilation-dir=C:\\\\Users\\\\sylva\\\\projekt\\\\sudokill\\\\build-linux\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-k66523" -resource-dir "C:\\\\Program Files\\\\LLVM\\\\lib\\\\clang\\\\19" -dependency-file "CMakeFiles\\\\cmTC_40780.dir\\\\CMakeCCompilerABI.c.o.d" -MT CMakeFiles/cmTC_40780.dir/CMakeCCompilerABI.c.o -sys-header-deps -internal-isystem "C:\\\\Program Files\\\\LLVM\\\\lib\\\\clang\\\\19\\\\include" -internal-isystem /usr/local/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_40780.dir/CMakeCCompilerABI.c.o -x c "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeCCompilerABI.c"
        clang -cc1 version 19.1.0 based upon LLVM 19.1.0 default target x86_64-pc-windows-msvc
        ignoring nonexistent directory "/usr/local/include"\x0d
        ignoring nonexistent directory "/include"\x0d
        ignoring nonexistent directory "/usr/include"\x0d
        #include "..." search starts here:\x0d
        #include <...> search starts here:\x0d
         C:\\Program Files\\LLVM\\lib\\clang\\19\\include\x0d
        End of search list.\x0d
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\clang.exe --target=x86_64-linux-gnu  -v -Wl,-v CMakeFiles/cmTC_40780.dir/CMakeCCompilerABI.c.o -o cmTC_40780   && cd ."
        FAILED: cmTC_40780 
        C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\clang.exe --target=x86_64-linux-gnu  -v -Wl,-v CMakeFiles/cmTC_40780.dir/CMakeCCompilerABI.c.o -o cmTC_40780   && cd ."
        clang version 19.1.0
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: C:\\Program Files\\LLVM\\bin
         "C:\\\\Program Files (x86)\\\\GNU Arm Embedded Toolchain\\\\10 2021.10\\\\arm-none-eabi\\\\bin\\\\ld.exe" --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -pie -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_40780 Scrt1.o crti.o crtbeginS.o -v CMakeFiles/cmTC_40780.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed crtendS.o crtn.o\x0d
        C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\arm-none-eabi\\bin\\ld.exe: unrecognised emulation mode: elf_x86_64\x0d
        Supported emulations: armelf\x0d
        clang: error: linker command failed with exit code 1 (use -v to see invocation)\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe"
    directories:
      source: "C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/CMakeScratch/TryCompile-zor21y"
      binary: "C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/CMakeScratch/TryCompile-zor21y"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_CXX_COMPILER_TARGET: "x86_64-linux-gnu"
      CMAKE_C_COMPILER_TARGET: "x86_64-linux-gnu"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/CMakeScratch/TryCompile-zor21y'
        
        Run Build Command(s): C:/ProgramData/chocolatey/bin/ninja.exe -v cmTC_b3f61
        [1/2] C:\\PROGRA~1\\LLVM\\bin\\clang.exe --target=x86_64-linux-gnu    -MD -MT CMakeFiles/cmTC_b3f61.dir/testCCompiler.c.o -MF CMakeFiles\\cmTC_b3f61.dir\\testCCompiler.c.o.d -o CMakeFiles/cmTC_b3f61.dir/testCCompiler.c.o -c C:/Users/sylva/projekt/sudokill/build-linux/CMakeFiles/CMakeScratch/TryCompile-zor21y/testCCompiler.c
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\clang.exe --target=x86_64-linux-gnu   CMakeFiles/cmTC_b3f61.dir/testCCompiler.c.o -o cmTC_b3f61   && cd ."
        FAILED: cmTC_b3f61 
        C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\clang.exe --target=x86_64-linux-gnu   CMakeFiles/cmTC_b3f61.dir/testCCompiler.c.o -o cmTC_b3f61   && cd ."
        C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\arm-none-eabi\\bin\\ld.exe: unrecognised emulation mode: elf_x86_64\x0d
        Supported emulations: armelf\x0d
        clang: error: linker command failed with exit code 1 (use -v to see invocation)\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
